<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>
<!-- 1) simple call-->
<script type="text/x-magento-init">

{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": {
                   "component": "Elogic_KoMage/js/plain-view-model"
                }
            }
        }
    }
}
</script>
<!--1) simple call-->
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>
</div>
