<?php

/**
 * @var \Elogic\MyAcordeon\Block\Display $block
 */
?>




<h1>Listen what did our customers said about our products</h1>

<div class="tabs">
    <ul id="tabs-nav">
        <li><a href="#tab1">Yurii</a></li>
        <li><a href="#tab2">Olha</a></li>
        <li><a href="#tab3">Oleh</a></li>
        <li><a href="#tab4">Max</a></li>
    </ul> <!-- END tabs-nav -->
    <div id="tabs-content">
        <div id="tab1" class="tab-content">
            <h2>Yurii</h2>
            <p>"I bought the iphone from this store. Simply amazing"</p>
        </div>
        <div id="tab2" class="tab-content">
            <h2>Olha</h2>
            <p>"Oh, i was happy that i can buy a new technique here, you need waste only 5 mins for doing that"</p>
        </div>
        <div id="tab3" class="tab-content">
            <h2>Oleh</h2>
            <p>"The best shop i ever used"</p>
        </div>
        <div id="tab4" class="tab-content">
            <h2>Max</h2>
            <p>"Nothing to say, everything is amazing"</p>
        </div>
    </div> <!-- END tabs-content -->
</div> <!-- END tabs -->

<script>

    require(['jquery', 'jquery/ui'], function($) {
        // Show the first tab and hide the rest
        $('#tabs-nav li:first-child').addClass('active');
        $('.tab-content').hide();
        $('.tab-content:first').show();

        // Click function
        $('#tabs-nav li').click(function(){
            $('#tabs-nav li').removeClass('active');
            $(this).addClass('active');
            $('.tab-content').hide();

            var activeTab = $(this).find('a').attr('href');
            $(activeTab).fadeIn();
            return false;
        });
    })
</script>



