
<a href="https://magento.test/">
<img src='<?php echo $this->getViewFileUrl('Elogic_MyWidget::images/arcana.png'); ?>' alt="image-icon" width="150" height="75">
</a>

<a href="https://magento.test/">
    <img src='<?php echo $this->getViewFileUrl('Elogic_MyWidget::images/arcana2.png'); ?>' alt="image-icon" width="150" height="75">
</a>

<a href="https://magento.test/">
    <img src='<?php echo $this->getViewFileUrl('Elogic_MyWidget::images/arcana3.png'); ?>' alt="image-icon" width="150" height="75">
</a>
