<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */


?>
<!-- 1) simple add without config-->
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "Elogic_SimpleRequireJsAdd/js/ola": {}-->
<!--        }-->
<!--    }-->
<!--</script>-->

<!--2) with config -->
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!---->
<!--        "*": {-->
<!--            "Elogic_SimpleRequireJsAdd/js/ola": {-->
<!--                "base_url": "--><?//= $block->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->

<!-- 3) "*" is meaning nothing select but we can specify any css selector for example div and our function will be caled for every single div-->
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "div": {-->
<!--            "Elogic_SimpleRequireJsAdd/js/ola": {-->
<!--                "base_url": "--><?//= $block->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->

<!-- 4) for special id selector-->
<!--<div id="testedRjs"></div>-->
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "#testedRjs": {-->
<!--            "Elogic_SimpleRequireJsAdd/js/ola": {-->
<!--                "base_url": "--><?//= $block->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->




<!-- 5 alternative - data mage init-->
<!--<div id="testedRjs" data-mage-init='{"Elogic_SimpleRequireJsAdd/js/ola": {"base_url": "/"}}'></div>-->

