<!--first metod via object manager but it's not good object-->
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
/** Apply filters here */
$collection = $productCollection->addAttributeToSelect('*')
    ->load();

foreach ($collection as $product){
    echo 'Name  =  '.$product->getName().' ';
}
?>
