<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">

{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "exampleUiComponent": {
                   "component": "Elogic_UiMage/js/plain-view-model"
                }
            }
        }
    }
}
</script>
<!--1) first ui component-->
<!--<div data-bind="scope: 'exampleUiComponent'">-->
<!--    <h3 data-bind="text: label"></h3>-->
<!--</div>-->


<!--2) add template -->
<div data-bind="scope: 'exampleUiComponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
